server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9080/realms/OneBank

# Keycloak Admin API Connection
keycloak:
  server-url: http://localhost:9080
  realm: master
  client-id: admin-cli
  username: admin
  password: admin
