server:
  port: 8085

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/OneBank
keycloak:
  server-url: http://localhost:8080
  realm: OneBank
  client-id: Product
  client-secret: A7zMEV2AyhSTGvWbyKKFlsadGjgCkioh